### ISSUE TITLE
Node + Yarn for React native projects

### ISSUE THREAD

**Issue by OleksandrKucherenko** [mreichelt/docker-android#18]
Hi, will be great one more variation with node and yarn tool installed.

That will be very good to have for ReactNative projects. Thanks

**Comment by OleksandrKucherenko** [comment]
Example from CircleCI: https://github.com/CircleCI-Public/example-images/blob/master/android/Dockerfile

**Comment by mreichelt** [comment]
Hey @OleksandrKucherenko! If you need more tools than are needed in these Docker images I suggest to create a new Docker image yourself - you can reference these here as base, and then add just the tools you need.

Of course it would be easy for me to add this, but the hard part actually is where to draw the line. Because if we add node and yarn, people will suggest we add all required software for Flutter / Cordova / Titanium / insert framework name here as well. And then we also have to keep track of just the right versions of those as well, leaving consumers unhappy if they can't get just the right version they need.
